version: "3"

services:
  postgres:
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./volumes/pgadmin:/root/.pgadmin
    ports:
      - "5433:80"
    restart: unless-stopped
    logging:
      driver: "none"
